#! /bin/bash
cd /Assignment1
N=100
a=0
b=1
for((i=0; i<=N; i++))
do
  echo "$a"
  c=$((a+b))
  a=$b
  b=$c
if(($a%2==0))
then
 echo "even Fibo Sequence: + $a">>even.txt
else
 echo "odd Fibonacci sequence: + $a">>odd.txt 
fi
done
Rajasekhara Reddy
